sudo: required
services:
  - docker

before_install:
  - docker build -t somyashastri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true somyashastri/docker-react npm run test

# use values from AWS, currently putting dummy values
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-208666926600"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
# create a user in aws in iam
# add keys in environment variables in travis ci
